// OSM links to specific country file containing the street name data plus the
// regions and all available countries.
import * as R from "./ramda.js"

export const osmLink = country => R.pipe(  
  // Select the region containing the searched country
  R.find(R.find(R.find(R.propEq(0, country)))),
  // Region's name
  R.head,
  region => `http://download.geofabrik.de/${region}/${country}-latest.osm.pbf`,    
)(regions)

// All countries, for all regions
const countryEntries = () => R.pipe(  
  R.chain(R.tail),  
  R.reduce(R.concat, [])
)(regions)

// Return a single `country` entry (name, frequency).
const countryEntry = country => R.find(R.propEq(0, country), countryEntries())
export const countries = R.compose(R.map(R.head), countryEntries)
export const countryEponymFrequency = R.compose(R.prop(1), countryEntry)

// All regions and countries as they appear in the openstreetmap (osm) database,
// http://download.geofabrik.de/
const regions = [
  // Region name (osm)
  ["africa", [
    // Country name (osm)            Eponym Minimum Frequency
    ["algeria",                      3],
    ["angola",                       2],
    ["benin",                        2],
    ["botswana",                     2],
    ["burkina-faso",                 2],
    ["burundi",                      2],
    ["cameroon",                     2],
    ["canary-islands",               2],      
    ["central-african-republic",     2],
    ["chad",                         2],
    ["congo-brazzaville",            2],
    ["congo-democratic-republic",    2],      
    ["egypt",                        3],      
    ["ethiopia",                     2],
    ["ghana",                        2],
    ["guinea",                       2],
    ["ivory-coast",                  2],
    ["kenya",                        2],
    ["liberia",                      2],
    ["libya",                        2],
    ["madagascar",                   2],
    ["malawi",                       2],
    ["mali",                         2],
    ["morocco",                      2],
    ["mozambique",                   2],
    ["namibia",                      2],
    ["nigeria",                      2],
    ["senegal-and-gambia",           2],
    ["south-africa",                 2],
    ["sudan",                        2],
    ["tanzania",                     3],
    ["togo",                         2],
    ["tunisia",                      2],
    ["uganda",                       2],
    ["zambia",                       2],
    ["zimbabwe",                     2],
  ]],
  
  ["central-america", [
    ["belize",                       2],
    ["costa-rica",                   2],
    ["cuba",                         2],
    ["el-salvador",                  2],
    ["guatemala",                    2],
    ["haiti-and-domrep",             2],
    ["honduras",                     2],
    ["jamaica",                      2],
    ["nicaragua",                    2],
    ["panama",                       2],
  ]],
   
  ["north-america", [
    ["canada",                       3],
    ["greenland",                    2],
    ["mexico",                       3],
    ["us",                           3],
  ]],
   
  ["south-america", [
    ["argentina",                    3],
    ["bolivia",                      2],
    ["brazil",                       3],
    ["chile",                        3],
    ["colombia",                     2],
    ["ecuador",                      2],
    ["guyana",                       2],
    ["paraguay",                     2],
    ["peru",                         2],
    ["suriname",                     2],
    ["uruguay",                      3],
    ["venezuela",                    2],
  ]],
   
  ["asia", [
    ["afghanistan",                  2],
    ["armenia",                      3],
    ["azerbaijan",                   2],
    ["bangladesh",                   3],
    ["bhutan",                       2],
    ["cambodia",                     2],
    ["china",                        3],
    ["gcc-states",                   3],
    ["india",                        3],
    ["indonesia",                    3],
    ["iran",                         3],
    ["iraq",                         3],
    ["israel-and-palestine",         3],
    ["japan",                        3],
    ["jordan",                       3],
    ["kazakhstan",                   3],
    ["kyrgyzstan",                   2],
    ["laos",                         2],
    ["lebanon",                      2],
    ["malaysia-singapore-brunei",    3],
    ["mongolia",                     3],
    ["myanmar",                      3],
    ["nepal",                        3],
    ["north-korea",                  3],
    ["pakistan",                     3],
    ["philippines",                  3],
    ["russia",                       3],
    ["south-korea",                  3],
    ["sri-lanka",                    3],
    ["syria",                        3],
    ["taiwan",                       3],
    ["tajikistan",                   2],
    ["thailand",                     3],
    ["turkmenistan",                 3],
    ["uzbekistan",                   3],
    ["vietnam",                      3],
    ["yemen",                        2],
  ]],
  
  ["europe", [
    ["albania",                      2],
    ["andorra",                      2],
    ["austria",                      3],
    ["azores",                       2],
    ["belarus",                      3],
    ["belgium",                      2],
    ["bosnia-herzegovina",           2],
    ["bulgaria",                     3],
    ["croatia",                      3],
    ["cyprus",                       2],
    ["czech-republic",               3],
    ["denmark",                      3],
    ["estonia",                      3],
    ["faroe-islands",                2],
    ["finland",                      3],
    ["france",                       3],
    ["georgia",                      3],
    ["germany",                      3],
    ["great-britain",                3],
    ["greece",                       3],
    ["guernsey-jersey",              2],
    ["hungary",                      2],
    ["iceland",                      2],
    ["ireland-and-northern-ireland", 2],
    ["isle-of-man",                  2],
    ["italy",                        3],
    ["kosovo",                       2],
    ["latvia",                       3],
    ["liechtenstein",                2],
    ["lithuania",                    3],
    ["luxembourg",                   2],
    ["macedonia",                    2],
    ["malta",                        2],
    ["moldova",                      2],
    ["monaco",                       2],
    ["montenegro",                   2],
    ["netherlands",                  3],
    ["norway",                       3],
    ["poland",                       3],
    ["portugal",                     3],
    ["romania",                      2],
    ["russia",                       2],
    ["serbia",                       2],
    ["slovakia",                     2],
    ["slovenia",                     3],
    ["spain",                        3],
    ["sweden",                       3],
    ["switzerland",                  3],
    ["turkey",                       3],
    ["ukraine",                      3],
  ]],

  ["australia-oceania", [
    ["american-oceania",             2],
    ["australia",                    3],      
    ["fiji",                         2], 
    ["new-caledonia",                2],
    ["new-zealand",                  3],      
    ["papua-new-guinea",             2],
    ["polynesie-francaise",          2],      
  ]]
]
